### PR TITLE
Switch to GitHub actions

### LINKED ISSUE #55: Switch to github actions
Switch CI to github actions so we can auto-release and test install from PyPI and conda.

### PR DESCRIPTION
**Pull request by znicholls**
# Pull request

Please confirm that this pull request has done the following:

- [x] Tests added (N/A)
- [x] Documentation added (where applicable) (N/A)
- [x] Example added (either to an existing notebook or as a new notebook, where applicable) (N/A)
- [x] Description in ``CHANGELOG.rst`` added

## Adding to CHANGELOG.rst

Please add a single line in the changelog notes similar to one of the following:

```
- (`#XX <https://github.com/znicholls/silicone/pull/XX>`_) Added feature which does something
- (`#XX <https://github.com/znicholls/silicone/pull/XX>`_) Fixed bug identified in (`#YY <https://github.com/znicholls/silicone/issues/YY>`_)
```

Closes #55

### CODE REVIEW

**Comment by znicholls** [comment]
@Rlamboll and @jkikstra just as fyi, all I've done here is replace our Travis checks with GitHub checks. Eventually we can expand to having more checks and automatically deploying to PyPI (if you want to see how that looks, have a look at https://github.com/znicholls/openscm-runner/tree/initial-setup/.github/workflows) but just want to do it bit by bit so there's not too many moving parts.

**Comment by znicholls** [comment]
Merge at will

**Comment by Rlamboll** [comment]
You requested @jkikstra review it too

**Comment by znicholls** [comment]
Oops true

**Pull request merged**
