### PR TITLE
Many notebooks

### PR DESCRIPTION
**Pull request by Rlamboll**
# Pull request

Please confirm that this pull request has done the following:

- [x] Tests added
- [x] Documentation added (where applicable)
- [x] Example added (either to an existing notebook or as a new notebook, where applicable)
- [x] Description in ``CHANGELOG.rst`` added

## Adding to CHANGELOG.rst

Please add a single line in the changelog notes similar to one of the following:

```
- (`#XX <https://github.com/znicholls/silicone/pull/XX>`_) Added feature which does something
- (`#XX <https://github.com/znicholls/silicone/pull/XX>`_) Fixed bug identified in (`#YY <https://github.com/znicholls/silicone/issues/YY>`_)
```

### CODE REVIEW

**Comment by Rlamboll** [comment]
This is mostly just splitting up the notebooks, I have reworded and expanded the section on the rolling windows quantile cruncher though, with a significant new final section. There are also minor changes to the way we get data from IIASA in order to streamline the notebooks and to allow for an update.

**Comment by jkikstra** [comment]
Thanks for splitting these up.

I found two more things in notebook 05. 
- For "DecomposeCollectionTimeDepRatio" I do not get what the output is supposed to explain to me; both `unit_consistant_db.variables(True)` and `results.variables()` give the basically the same output. Could you clarify?
- Under "calculate aggregate values" could you just add that 'using AR5 conversion factors' is done by setting the boolean `use_AR4_data=False`?

**Comment by Rlamboll** [comment]
Thanks @jkikstra, however I will need to merge #49 first. Maybe you can review the non-notebook parts of that too since @znicholls has a large to-do list.

**Comment by jkikstra** [comment]
I don't think I'll be able to do that this week still unfortunately.

**Comment by znicholls** [comment]
this should be gtg once #49 is done (hopefully also not far off)

**Pull request merged**
