### PR TITLE
Eqw notebook

### PR DESCRIPTION
**Pull request by Rlamboll**
# Pull request

Please confirm that this pull request has done the following:

- [x] Tests added
- [x] Documentation added (where applicable)
- [x] Example added (either to an existing notebook or as a new notebook, where applicable)
- [x] Description in ``CHANGELOG.rst`` added

## Adding to CHANGELOG.rst

Please add a single line in the changelog notes similar to one of the following:

```
- (`#XX <https://github.com/znicholls/silicone/pull/XX>`_) Added feature which does something
- (`#XX <https://github.com/znicholls/silicone/pull/XX>`_) Fixed bug identified in (`#YY <https://github.com/znicholls/silicone/issues/YY>`_)
```

### CODE REVIEW

**Comment by znicholls** [comment]
@Rlamboll can I rebased and force push (or jump on a call and talk you through how to do so)?

**Comment by Rlamboll** [comment]
Sure, I did attempt to rebase this on master (although after I had rebased it on some other things first, in case that makes a difference).

**Comment by znicholls** [comment]
fyi this will mean that you have to update your local branch (if you just want to simply overwrite all your local changes you could do e.g. `git fetch origin;git reset --hard origin/EQW_notebook` but if you have local changes you want to keep that's probably a bad idea...)

**Comment by Rlamboll** [comment]
hmm, that's very easily done using the plotting function, which produces these mechanically. The reason I hesitate is that we were considering taking that out and putting it in the other repository.

**Comment by znicholls** [comment]
> hmm, that's very easily done using the plotting function, which produces these mechanically. The reason I hesitate is that we were considering taking that out and putting it in the other repository

maybe just rip the code out and put it standalone in the notebook?

**Comment by Rlamboll** [comment]
OK, that should do the trick. I'm clocking off for the night.

**Comment by znicholls** [comment]
> OK, that should do the trick

Sorry I meant the same quantile plot, but for the equal quantile walk only. That would illustrate that  there's a one to one mapping in the equal quantile walk (which can then be compared to the quantile rolling windows cruncher which allows the user to pick the quantile of interest rather than it always being 'equal').

**Comment by Rlamboll** [comment]
But EQW doesn't use the relationship between gases, so gas X vs gas y doesn't make sense. It would just be two separate cumulative density plots over different intervals

**Comment by znicholls** [comment]
That’s why I suggested the joint plot, it highlights that you’re using two
separate densities and that the relationship doesn’t actually get used so
you can get some funny looking relationships.

**Comment by Rlamboll** [comment]
OK @znicholls, I've also had to disable the import data test as the database seems to be down quite often atm and except connectionError doesn't seem to work.

**Comment by znicholls** [comment]
> except connectionError doesn't seem to work

Oh right you need to import it from the requests library. See #98 (also contains extra plot for EQW demo).

**Pull request merged**
